# Generated by Django 2.2.24 on 2022-12-09 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='flat',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
