# Generated by Django 2.2.24 on 2022-12-09 18:12

from django.db import migrations

import phonenumbers


def make_pure_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        phone_number = phonenumbers.parse(flat.phonenumber, 'RU')
        flat.pure_phonenumber = ''
        if phonenumbers.is_valid_number_for_region(phone_number, 'RU'):
            flat.pure_phonenumber = f'+{phone_number.country_code}{phone_number.national_number}'
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20221209_2107'),
    ]

    operations = [
        migrations.RunPython(make_pure_phonenumber)
    ]