# Generated by Django 2.2.24 on 2022-12-09 18:22

from django.db import migrations


def fill_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            full_name=flat.owner,
            owners_phonenumber=flat.phonenumber,
            owner_pure_phone=flat.pure_phonenumber)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20221209_2121'),
    ]

    operations = [
        migrations.RunPython(fill_owner)
    ]
