# Generated by Django 2.2.24 on 2022-12-09 18:37

from django.db import migrations


def fill_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        flat.owners.set(
            Owner.objects.filter(
            full_name=flat.owner,
            owners_phonenumber=flat.phonenumber,
            )
        )

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221209_2122'),
    ]

    operations = [
        migrations.RunPython(fill_flat)
    ]
